import bodyParser from 'body-parser';
import express from 'express'
import mongoose from 'mongoose'
import jwt from 'jsonwebtoken'
import dotenv from "dotenv"
import cors from 'cors'
import cvUserRoutes from './routes/cvUserRoutes.js';
import skillsRoutes from './routes/skillsroutes.js';
import certificates from './routes/certificatesRoutes.js';
import refereeRoutes from './routes/refereesRoutes.js';
import educationRoutes from './routes/educationRoutes.js';
import ExperienceRoutes from './routes/experienceRoutes.js';
import ProjectRouter from './routes/projectsRouter.js';
import userRouter from './routes/userRoutes.js';
import cookieParser from 'cookie-parser';
